---
# tasks file for launch_virts
#- name: download boxe
#  get_url:
#    url: https://app.vagrantup.com/ubuntu/boxes/focal64/versions/20230615.0.0
#    dest: /home/konstantin/.vagrant.d/boxes/focal-server-cloudimg-amd64-vagrant.box
#  environment:
#    https_proxy: "http://172.16.55.99:8080"

- name: vagrant up
  shell: |
    cd /home/konstantin/ansible/project/
    vagrant up
  become_user: konstantin