- hosts: myhosts
#  strategy: debug
  pre_tasks:
    - ping:
    - debug:
#    - apt: update_cache=yes
  roles:
    - { role: vagrant_box, tags: [get_box, vagrant_init]}
    - { role: vagrant, tags: [vg_instal]}
    - { role: launch_virts, tags: [start_vm]}


- hosts: virtuals
  pre_tasks:
    - ping:
      tags: ping_all
    - apt: update_cache=yes
      tags: update_virts

- hosts: db
  become: yes
  vars_files:
    - vars/db.yml
    - vars/wp-vault.yml
  pre_tasks:
    - debug:    
  vars:
    mysql_bind_address: '0.0.0.0'
  roles:
    - { role: geerlingguy.mysql, tags: setup_db }

- hosts: web_app1,web_app2
  become: yes
  pre_tasks:
    - debug:

  vars:
    php_version: '7.4'
    php_webserver_daemon: "nginx"
  vars_files:
    - vars/db.yml
    - vars/wp-vault.yml
    - ../roles/wordpress/vars/wordpress.yml
  roles:
    - { role: copy_ssl_certs, tags: setup_nginx }
    - { role: geerlingguy.nginx, tags: setup_nginx }
    - { role: geerlingguy.php, tags: setup_php } 
    - { role: wordpress, tags: setup_wp }
  post_tasks:
    - service: name=nginx state=restarted
