all:
  children:
    myhosts:
      hosts:
        localhost:
          ansible_user: konstantin
    # proxy:
    #   hosts:
    #     proxy_host:
    #       ansible_host: 192.168.56.10
    # web_apps:
    #   hosts:
    #     web_app1:
    #       ansible_host: 192.168.56.11
    #     web_app2:
    #       ansible_host: 192.168.56.12          
    # database:
    #   hosts:
    #     db:
    #       ansible_host: 192.168.56.13
    # monitoring:
    #   hosts:
    #     monitor:
    #       ansible_host: 192.168.56.14
    virtuals:
      hosts:
        proxy:
          ansible_host: 192.168.56.10        
        web_app1:
          ansible_host: 192.168.56.11
        web_app2:
          ansible_host: 192.168.56.12 
        db:
          ansible_host: 192.168.56.13
        monitor:
          ansible_host: 192.168.56.14