---
# tasks file for monitoring
- name: install prometheus
  apt:
    name: prometheus
    state: "present"

- name: download apt-key
  get_url: 
    url: https://dl.grafana.com/oss/release/grafana_10.0.1_amd64.deb
    dest: /tmp/grafana_10.0.1_amd64.deb
  environment:
    https_proxy: "http://172.16.55.99:8080"

- name: install deb packege grafana
  apt:
    deb: /tmp/grafana_10.0.1_amd64.deb

- name: start grafana
  systemd:
    name: grafana-server
    state: started
    enabled: true

- name: add host to prometheus
  lineinfile:
    path: /etc/prometheus/prometheus.yml
    line: "      - targets: ['{{item}}:9100']"
  # loop: "{{ group['virtuals'] }}"
  with_items:
    - 192.168.56.10  
    - 192.168.56.11    
    - 192.168.56.12 
    - 192.168.56.13
  notify: restart_prometheus